project:
  type: website

website:
  title: "Proyectos reproducibles con renv"
  navbar:
    left:
      - href: index.qmd
        text: Intro a renv
      - about.qmd
      - href: slides.qmd
        text: Presentación

format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss
    toc: true



